### ISSUE TITLE
Subtrees with EXPORT_FILE_NAME cannot be nested

### ISSUE THREAD

**Issue by kaushalmodi** [Robin-Wils/robinwils.gitlab.io#1]
I looked at your Org file: https://github.com/Robin-Wils/robinwils.gitlab.io/blame/9655901c20b8e848dc042915b30e372268c3060e/content-org/website.org#L31-L45

![image](https://user-images.githubusercontent.com/3578197/64640581-483f1080-d3d8-11e9-9467-08ff115eaad5.png)

As I mentioned in the Mastodon thread, `ox-hugo` does not support nesting of EXPORT_FILE_NAME propertied subtrees.

**Comment by Robin-Wils** [comment]
Thanks for making time and looking into this!   
I hope that I don't have to bother you anymore.  

This fixes other problems aswell. I can run hugo locally again for example.

**Comment by kaushalmodi** [comment]
No problem at all! I appreciated that you reached out with questions. Feel free to do that again. 

Did all the changes in the website.org file in the last 2 PR's make complete sense?

**Comment by Robin-Wils** [comment]
Yes, they did make sense!
